(setq mew-config-alist '((default
                           (name "Guiqiang Wang")
                           (user "wgq_hit")
                           (mail-domain "126.com")
                           (mailbox-type imap)
                           (proto "%")
                           (imap-server "imap.126.com")
                           (imap-user "wgq_hit")
                           (imap-auth t)
                           (imap-ssl t)
                           (imap-ssl-port 993)
                           (imap-size 0)
                           (imap-delete t)
                           (smtp-server "smtp.126.com")
                           (smtp-user "wgq_hit")
                           (smtp-auth-list ("LOGIN" "PLAIN" "CRAM-MD5"))
                           (smtp-ssl . t)
                           (smtp-ssl-port 465))
                         (netease
                          (name "Guiqiang Wang")
                          (user "wgq_713")
                          (mail-domain "163.com")
                          (mailbox-type imap)
                          (proto "%")
                          (imap-server "imap.163.com")
                          (imap-user "wgq_713")
                          (imap-auth t)
                          (imap-ssl t)
                          (imap-ssl-port 993)
                          (imap-size 0)
                          (imap-delete t)
                          (smtp-server "smtp.163.com")
                          (smtp-user "wgq_713")
                          (smtp-auth-list ("LOGIN" "PLAIN" "CRAM-MD5"))
                          (smtp-ssl . t)
                          (smtp-ssl-port 465))
                         (hotmail
                          (name "Guiqiang Wang")
                          (user "wguiqiang")
                          (mail-domain "hotmail.com")
                          (mailbox-type imap)
                          (proto "%")
                          (imap-server "imap-mail.outlook.com")
                          (imap-user "wguiqiang@hotmail.com")
                          (imap-auth t)
                          (imap-ssl t)
                          (imap-ssl-port 993)
                          (imap-size 0)
                          (imap-delete t)
                          ;; hotmail只支持starttls，不支持ssl。
                          (smtp-server "smtp-mail.outlook.com")
                          (smtp-user "wguiqiang@hotmail.com")
                          (smtp-auth-list ("LOGIN" "PLAIN" "CRAM-MD5"))
                          (smtp-ssl . t)
                          (smtp-ssl-port 465)
                          )
                         (qq
                          (name "Guiqiang Wang")
                          (user "278064399")
                          (mail-domain "qq.com")
                          (mailbox-type imap)
                          (proto "%")
                          (imap-server "imap.qq.com")
                          (imap-user "278064399")
                          (imap-auth t)
                          (imap-ssl t)
                          (imap-ssl-port 993)
                          (imap-size 0)
                          (imap-delete t)
                          (smtp-server "smtp.qq.com")
                          (smtp-user "278064399")
                          (smtp-auth-list ("LOGIN" "PLAIN" "CRAM-MD5"))
                          (smtp-ssl . t)
                          (smtp-ssl-port 465))))
