(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
 '(vundo lingva modelica-mode posframe all-the-icons-dired delight all-the-icons dired-subtree ivy-bibtex key-chord org-appear vcard semi ox-pandoc restclient dired-du yasnippet-snippets meghanada org-pdftools org-brain rg baidu-translate unicode-escape pdfgrep jedi find-file-in-project gnu-elpa-keyring-update jupyter ace-jump-helm-line ebib exec-path-from-shell dired-filetype-face matlab-mode academic-phrases auto-yasnippet org-ref org-noter yaml-mode term-keys diminish sudo-edit youdao-dictionary pyim pyim-basedict helm-pass pass helm-mu mu4e-alert ztree wrap-region window-numbering which-key web-mode w3m volatile-highlights vlf visual-regexp visible-mark vimish-fold use-package tangotango-theme smartrep smart-mode-line skewer-mode recentf-ext readline-complete rainbow-mode rainbow-delimiters quickrun popup-kill-ring pinyin-search peep-dired pdf-tools paredit-everywhere outline-magic operate-on-number nyan-mode neotree navi-mode names multiple-cursors multifiles markdown-mode magit magic-latex-buffer lacarte ivy-hydra interleave imenu-anywhere hungry-delete highlight-symbol highlight-parentheses helm-unicode helm-swoop helm-projectile helm-gtags helm-flyspell helm-flycheck helm-firefox helm-descbinds helm-bm helm-bibtex helm-ag graphviz-dot-mode goto-chg google-translate god-mode gnuplot-mode git-timemachine function-args flycheck-pos-tip fcitx expand-region evil-nerd-commenter eshell-prompt-extras emms emmet-mode elpy elmacro elisp-slime-nav easy-kill dumb-jump drag-stuff disaster dired-ranger dired-narrow diff-hl counsel company-web company-try-hard company-quickhelp company-c-headers clipmon clean-aindent-mode cdlatex buttercup bing-dict backup-walker avy-zap auto-highlight-symbol auto-complete-clang auto-complete-c-headers auto-complete-auctex auctex-latexmk arduino-mode anzu anchored-transpose aggressive-indent ace-pinyin ace-link ac-math ac-ispell ac-html-bootstrap)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(diredp-compressed-file-suffix ((t (:foreground "#7b68ee"))) t)
 '(diredp-ignored-file-name ((t (:foreground "#aaaaaa"))) t)
 '(helm-buffer-directory ((t (:foreground "yellow" :weight bold))))
 '(helm-buffer-file ((t (:inherit font-lock-type-face))))
 '(helm-ff-directory ((t (:foreground "yellow" :weight bold))))
 '(helm-ff-dotted-directory ((t (:foreground "yellow" :weight bold))))
 '(helm-ff-file ((t (:foreground "white"))))
 '(helm-grep-file ((t (:foreground "cyan"))))
 '(helm-selection ((t (:background "black" :underline t))))
 '(helm-visible-mark ((t (:foreground "DeepSkyBlue1"))))
 '(ido-first-match ((t (:foreground "yellow" :weight bold))))
 '(ido-only-match ((((class color)) (:foreground "DeepSkyBlue1" :weight bold))))
 '(ido-subdir ((t (:foreground "green"))))
 '(org-code ((t :inherit shadow)))
 '(org-extra-emphasis-01 ((t (:foreground "red" :underline t :inherit org-extra-emphasis))))
 '(org-extra-emphasis-02 ((t (:foreground "orange" :underline t :inherit org-extra-emphasis))))
 '(org-extra-emphasis-03 ((t (:foreground "yellow" :underline t :inherit org-extra-emphasis))))
 '(org-extra-emphasis-04 ((t (:foreground "green" :underline t :inherit org-extra-emphasis))))
 '(org-extra-emphasis-05 ((t (:foreground "cyan" :underline t :inherit org-extra-emphasis))))
 '(org-extra-emphasis-06 ((t (:foreground "DodgerBlue" :underline t :inherit org-extra-emphasis))))
 '(org-extra-emphasis-07 ((t (:foreground "SlateBlue" :underline t :inherit org-extra-emphasis))))
 '(org-extra-emphasis-08 ((t (:foreground "orchid" :underline t :inherit org-extra-emphasis))))
 '(org-extra-emphasis-09 ((t (:background "DarkOrchid" :inherit org-extra-emphasis))))
 '(org-extra-emphasis-10 ((t (:background "DarkSlateBlue" :inherit org-extra-emphasis))))
 '(org-extra-emphasis-11 ((t (:background "DarkBlue" :inherit org-extra-emphasis))))
 '(org-extra-emphasis-12 ((t (:background "DarkCyan" :inherit org-extra-emphasis))))
 '(org-extra-emphasis-13 ((t (:background "DarkGreen" :inherit org-extra-emphasis))))
 '(org-extra-emphasis-14 ((t (:background "DarkGoldenrod" :inherit org-extra-emphasis))))
 '(org-extra-emphasis-15 ((t (:background "DarkOrange" :inherit org-extra-emphasis))))
 '(org-extra-emphasis-16 ((t (:background "DarkRed" :inherit org-extra-emphasis))))
 '(org-meta-line ((t :inherit (font-lock-comment-face))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "yellow"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "green"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "DeepSkyBlue1"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#8b7500"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#8b7500"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#8b7500"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#8b7500"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#8b7500"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#8b7500"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "red"))))
 '(sml/col-number ((t (:foreground "lawn green"))))
 '(sml/filename ((t (:inherit sml/global :foreground "yellow" :weight bold))))
 '(sml/line-number ((t (:foreground "gold"))))
 '(sml/modes ((t (:inherit sml/global :foreground "gray50"))))
 '(sml/numbers-separator ((t (:inherit sml/global))))
 '(sml/position-percentage ((t (:foreground "yellow"))))
 '(sml/prefix ((t (:inherit sml/global :foreground "deep sky blue" :weight bold))))
 '(sml/projectile ((t (:foreground "deep sky blue" :weight bold))))
 '(sml/read-only ((t (:inherit sml/not-modified :foreground "gray50")))))
