("compressed" "data" "office" "images" "movie" "text" "scripts" "source" "builder")

(("compressed" (:foreground "steel blue") "zip rar tar gz bz2 7z" nil nil nil nil)
 ("data" (:foreground "DeepSkyBlue") "xml yaml json csv odg vsd pdf djvu" nil nil nil t)
 ("office" (:foreground "tomato") "doc docx ppt pptx xls xlsx dxf dwg" nil nil nil t)
 ("images" (:foreground "violet") "jpe?g gif png bmp eps ps svg xpm pbm ico xbm ai tiff?" nil nil nil t)
 ("movie" (:foreground "orange") "mp3 ape rm rmvb avi mp4 mkv flv f4v mpg 3gp wmv mov asf mpeg wma" nil nil nil nil)
 ("text" (:foreground "chartreuse") "txt text rst markdown md org tex gp dot" nil nil nil t)
 ("scripts" (:foreground "khaki") "rb py pyc pyo el lisp scm sh" nil nil nil nil)
 ("source" (:foreground "cyan") "c h cpp cxx hpp m htm html j2 js" nil nil nil nil)
 ("builder" (:foreground "magenta") "Makefile configure *.spec *.make *.rules" t nil nil nil))
