(setq mew-config-alist '((default
                           (mailbox-type pop)
                           (name "Guiqiang Wang")
                           (user "wgq_hit")
                           (mail-domain "126.com")
                           (smtp-server "smtp.126.com")
                           (smtp-user "wgq_hit")
                           (smtp-auth-list ("LOGIN" "PLAIN" "CRAM-MD5"))
                           (smtp-ssl . t)
                           (smtp-ssl-port "465")
                           (pop-server "pop.126.com")
                           (pop-user "wgq_hit")
                           (pop-auth pass)
                           (pop-ssl t)
                           (pop-ssl-port "995"))
                         (netease
                          (mailbox-type pop)
                          (name "Guiqiang Wang")
                          (user "wgq_713")
                          (mail-domain "163.com")
                          (smtp-server "smtp.163.com")
                          (smtp-user "wgq_713")
                          (smtp-auth-list ("LOGIN" "PLAIN" "CRAM-MD5"))
                          (smtp-ssl . t)
                          (smtp-ssl-port "465")
                          (pop-server "pop.163.com")
                          (pop-user "wgq_713")
                          (pop-auth pass)
                          (pop-ssl t)
                          (pop-ssl-port "995"))
                         (hotmail
                          (mailbox-type pop)
                          (name "Guiqiang Wang")
                          (user "wguiqiang")
                          (mail-domain "hotmail.com")
                          (smtp-server "smtp-mail.outlook.com")
                          (smtp-user "wguiqiang@hotmail.com")
                          (smtp-auth-list ("LOGIN" "PLAIN" "CRAM-MD5"))
                          (smtp-ssl . t)
                          (smtp-ssl-port "587")
                          (pop-server "pop-mail.outlook.com")
                          (pop-user "wguiqiang@hotmail.com")
                          (pop-auth pass)
                          (pop-ssl t)
                          (pop-ssl-port "995"))
                         (qq
                          (mailbox-type pop)
                          (name "Guiqiang Wang")
                          (user "278064399")
                          (mail-domain "qq.com")
                          (smtp-server "smtp.qq.com")
                          (smtp-user "278064399")
                          (smtp-auth-list ("LOGIN" "PLAIN" "CRAM-MD5"))
                          (smtp-ssl . t)
                          (smtp-ssl-port "587")
                          (pop-server "pop.qq.com")
                          (pop-user "278064399")
                          (pop-auth pass)
                          (pop-ssl t)
                          (pop-ssl-port "995"))))
