#!/bin/zsh

function widget-swint-locate()
{
    local selected=$(locate ~/ | percol --match-method pinyin)
    if [ $? -eq 0 ]; then
        local new_left="${LBUFFER} ${selected} "
        BUFFER=${new_left}${RBUFFER}
        CURSOR=${#new_left}
    fi
    zle reset-prompt
}

widget-swint-locate "$@"
