#!/bin/zsh

function widget-percol-cd-history() {
    local destination=$(percol-get-destination-from-history)
    if [[ $destination != "" ]]; then
        cd ${destination/#\~/${HOME}}
    fi
    zle reset-prompt
}

widget-percol-cd-history "$@"
