(setq mew-config-alist '(
                         ("default"
                          ("name"         .  "Guiqiang Wang")
                          ("user"         .  "wgq_hit")
                          ("mail-domain"  .  "126.com")
                          ("mailbox-type" .  pop)
                          ("smtp-server"  .  "smtp.126.com")
                          ("smtp-user"    .  "wgq_hit")
                          ("smtp-auth-list" . ("LOGIN" "PLAIN" "CRAM-MD5"))
                          ("smtp-port"    .  "25")
                          ("pop-server"   .  "pop.126.com")
                          ("pop-user"     .  "wgq_hit")
                          ("pop-auth"     .  pass)
                          ("pop-port"     .  "110")
                          ;; ("smtp-ssl" . t)
                          ;; ("smtp-ssl-port" "465")
                          ;; ("pop-ssl" t)
                          ;; ("pop-ssl-port" "995")
                          )
                         ("163"
                          ("name"         .  "Guiqiang Wang")
                          ("user"         .  "wgq_713")
                          ("mail-domain"  .  "163.com")
                          ("mailbox-type" .  pop)
                          ("smtp-server"  .  "smtp.163.com")
                          ("smtp-user"    .  "wgq_713")
                          ("smtp-auth-list" . ("LOGIN" "PLAIN" "CRAM-MD5"))
                          ("smtp-port"    .  "25")
                          ("pop-server"   .  "pop.163.com")
                          ("pop-user"     .  "wgq_713")
                          ("pop-auth"     .  pass)
                          ("pop-port"     .  "110")
                          ;; ("smtp-ssl" . t)
                          ;; ("smtp-ssl-port" "465")
                          ;; ("pop-ssl" t)
                          ;; ("pop-ssl-port" "995")
                          )
                         ))
(setq mew-ssl-verify-level 0)
